### ISSUE TITLE
Add support for regex paths

### ISSUE THREAD

**Issue by ValkyrieOps** [sensu/sensu-check-log#10]
It would be helpful to be able to specify a regex path/multiple files to look at, specifically for applications that write logs to dated folders.  For example:

`C:\Program Files\Application\logs\YYYY-MM-DD\log.txt`

Being able to present the check configuration as the following would be nice.

`sensu-check-log -log "C:\Program Files\Application\logs\*\*.txt" -match ERROR -state "C:\etc\sensu\log_state\Application"`

This was previously accomplished with a modified version of the log plugin for Sensu Core, but given the current Ruby runtime does not support Windows that guy no longer functions.

**Comment by ValkyrieOps** [comment]
I went ahead and reworked this for my use case using the asset template as a starting point and pulled in what was useful.  Hope that's all right.  Suggestions are welcome for improvements: https://github.com/ValkyrieOps/sensu-check-log-regex.  Can close this out too I suppose.

**Comment by jspaleta** [comment]
Hey @ValkyrieOps ,
Of course its all right.

I'm going to be working on updating this to use the plugin SDK this week, reusing some of your regex logic work but keeping the events api logic to generate different events.  

If you are interested in working towards deprecating your spin-off and want to eventually use this plugin, please file additional feature requests (after I get this initial refactor done) that bring the two repos into feature parity.

**Comment by ValkyrieOps** [comment]
Excellent really excited for the new changes!  I will take a look at integrating this once that PR goes through.  Once that's done I can deprecate the existing repo and delete the Bonsai Asset as well.  Cheers
